Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.Models;

using PagedList;
using PagedList.Mvc;
namespace MvcBookStore.Views.Bookstore
{
    public class BookStoreController : Controller
    {
        // GET: BookStore
        QLBANSACHEntities data = new QLBANSACHEntities();

        private List<SACH> getSachMoi(int i)
        {
            return data.SACHes.OrderByDescending(s => s.Ngaycapnhat)
                                  .Take(i)
                                  .ToList();
        }
        public ActionResult Index(int ? page)
        {
            int pageSize = 6;
            int pageNum = page ?? 1;
            // Lấy 5 quyển sách mới nhất
            var latestBooks = getSachMoi(15);
                return View(latestBooks.ToPagedList(pageNum,pageSize));
     
        }
        public ActionResult Take() {
            // Lấy 5 quyển sách mới nhất
            var latestBooks = data.SACHes
                                  .OrderByDescending(s => s.Ngaycapnhat)
                                  .Take(5)
                                  .ToList();

            return View(latestBooks);
        }
        public ActionResult Topic() {
            var topic = from cd in data.CHUDEs select cd;
            return PartialView(topic);
        }
        public ActionResult NhaXuatBan()
        {
            var chude = from cd in data.NHAXUATBANs select cd;
            return PartialView(chude);
        }
        public ActionResult Details(int id) {
            var sach = from s in data.SACHes
                       where s.Masach == id
                       select s;
            return View(sach.Single());
        }

        public ActionResult SPTheoChude(int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach);
        }

    }
}

Controllers/NguoiDungController.cs
using MvcBookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBookStore.Controllers
{

    public class NguoiDungController : Controller
    {
        private readonly QLBANSACHEntities db = new QLBANSACHEntities();
        // GET: NguoiDung
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection collection, KHACHHANG kh)
        {
            // Gán các giá trị người dùng nhập liệu cho các biến
            var hoten = collection["HotenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Matkhaunhaplai"];
            var diachi = collection["Diachi"];
            var email = collection["Email"];
            var dienthoai = collection["Dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["Ngaysinh"]);

            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được để trống";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Phải nhập mật khẩu";
            }
            else if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi4"] = "Phải nhập lại mật khẩu";
            }
            else if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Email không được bỏ trống";
            }
            else if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi6"] = "Phải nhập điện thoại";
            } else if (String.IsNullOrEmpty(diachi))
            {
                ViewData["Loi7"] = "Phải nhập địa chỉ";
            }
            else
            {
                // Gán giá trị cho đối tượng được tạo mới (kh)
                kh.HoTen = hoten;
                kh.Taikhoan = tendn;
                kh.Matkhau = matkhau;
                kh.Email = email;
                kh.DiachiKH = diachi;
                kh.DienthoaiKH = dienthoai;
                kh.Ngaysinh = DateTime.Parse(ngaysinh);

                //db.KHACHHANGs.Add(kh);
                //db.SaveChanges();
                //return RedirectToAction("Dangnhap");
                try
                {
                    db.KHACHHANGs.Add(kh);
                    db.SaveChanges();
                    return RedirectToAction("Dangnhap");
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Error: " + ex.Message); // Hiển thị lỗi ra console
                    ViewBag.Error = "Có lỗi xảy ra: " + ex.Message; // Hoặc hiển thị trên giao diện
                   
                }
            }
            ViewData["Loi8"] = "Email tồn tại hoặc là tài khoản tồn tại";
            return this.DangKy();

        }

       
        public ActionResult DangNhap(FormCollection collection)
        {
            // Gán các giá trị người dùng nhập liệu cho các biến
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];

            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                // Gán giá trị cho đối tượng được tạo mới (kh)
                KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(
                    n => n.Taikhoan == tendn && n.Matkhau == matkhau);

                if (kh != null)
                {
                    ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";
                    Session["Taikhoan"] = kh;
                    return RedirectToAction("Index", "Bookstore");
                }
                else
                {
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            return View();
        }
       



    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta name="keywords" content="Shoe Store, Free Template, templatemo.com" />
    <meta name="description" content="Shoe Store - Free Website Template provided by templatemo.com" />
    <link href="~/Content/templatemo_style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="~/Content/styles.css" />





    <script language="javascript" type="text/javascript">
        function clearText(field) {
            if (field.defaultValue == field.value) field.value = '';
            else if (field.value == '') field.value = field.defaultValue;
        }
    </script>

    <script language="javascript" type="text/javascript" src="~/Scripts/mootools-1.2.1-core.js"></script>
    <script language="javascript" type="text/javascript" src="~/Scripts/mootools-1.2-more.js"></script>
    <script language="javascript" type="text/javascript" src="~/Scripts/slideitmoo-1.1.js"></script>
    <script language="javascript" type="text/javascript">
        window.addEvents({
            'domready': function () {
                /* thumbnails example , div containers */
                new SlideItMoo({
                    overallContainer: 'SlideItMoo_outer',
                    elementScrolled: 'SlideItMoo_inner',
                    thumbsContainer: 'SlideItMoo_items',
                    itemsVisible: 6,
                    elemsSlide: 2,
                    duration: 160,
                    itemsSelector: '.SlideItMoo_element',
                    itemWidth: 140,
                    showControls: 1
                });
            },

        });
    </script>
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
    @*<script>
        tinymce.init({
            selector: 'texarea[name="Mota"]',
            menubar: true,
            plugins: 'lists link image charmap print preview hr anchor pagebreak',
            toolbar_mode: 'floating',
            toolbar: 'undo redo | formatselect | bold italic backcolor | ' +
                'alignleft aligncenter alignright alignjustify | ' +
                'bullist numlist outdent indent | removeformat | help',
            // Đảm bảo không có cấu hình nào như "hidden" hoặc "visibility: hidden"
            setup: function (editor) {
                editor.on('init', function () {
                    document.getElementById("mce_0").style.visibility = "visible";
                });
            }
        });
    </script>*@

</head>
<body>
    <div id="templatemo_menu_wrapper">

        <div id="templatemo_menu">

            <ul>
                <li><a href="@Url.Action("Index", "Admin")" class="current">Trang chủ</a></li>

                <li>
                    <a href="@Url.Action("Sanoham", "Admin")" target="_parent">Quản lí chủ đề</a>
                </li>
                <li>
                    <a href="@Url.Action("Nhaxuatban", "Admin")" target="_parent">Quản lí NXB</a>
                </li>
                <li>

                    <a href="@Url.Action("Sach", "Admin")" target="_parent">Quản lí sách</a>

                </li>
                <li>

                    <a href="@Url.Action("ThongKe", "Admin")" target="_parent">Thống kê sách</a>

                </li>

            </ul>

        </div> <!-- end of templatemo_menu -->

    </div> <!-- end of templatemo_menu_wrapper -->

   

    <div id="templatemo_content_wrapper">
       

        <div >
           

            <div class="content_section">




                @RenderBody();


                <div class="cleaner"></div>

            </div>

        </div> <!-- end of templatemo_content -->

        <div class="cleaner"></div>

    </div> <!-- end of templatemo_content_wrapper -->

    <div id="templatemo_footer">

        <ul class="footer_menu">
            <li><a href="#">Home</a></li>
            <li><a href="#">Products</a></li>
            <li><a href="#">News</a></li>
            <li><a href="#">Gallery</a></li>
            <li class="last_menu"><a href="#">Contact</a></li>
        </ul>

        Copyright © 2048 <a href="#">Your Company Name</a> |
        <a href="http://www.iwebsitetemplate.com" target="_parent">Website Templates</a> by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a>
    </div>
    <!-- end of footer -->

</body>
</html>

Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Shoe Store - Free Template</title>
    <meta name="keywords" content="Shoe Store, Free Template, templatemo.com" />
    <meta name="description" content="Shoe Store - Free Website Template provided by templatemo.com" />
    <link href="~/Content/templatemo_style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="~/Content/styles.css" />

    <script language="javascript" type="text/javascript">
        function clearText(field) {
            if (field.defaultValue == field.value) field.value = '';
            else if (field.value == '') field.value = field.defaultValue;
        }
    </script>

    <script language="javascript" type="text/javascript" src="~/Scripts/mootools-1.2.1-core.js"></script>
    <script language="javascript" type="text/javascript" src="~/Scripts/mootools-1.2-more.js"></script>
    <script language="javascript" type="text/javascript" src="~/Scripts/slideitmoo-1.1.js"></script>
    <script language="javascript" type="text/javascript">
        window.addEvents({
            'domready': function () {
                /* thumbnails example , div containers */
                new SlideItMoo({
                    overallContainer: 'SlideItMoo_outer',
                    elementScrolled: 'SlideItMoo_inner',
                    thumbsContainer: 'SlideItMoo_items',
                    itemsVisible: 6,
                    elemsSlide: 2,
                    duration: 160,
                    itemsSelector: '.SlideItMoo_element',
                    itemWidth: 140,
                    showControls: 1
                });
            },

        });
    </script>
</head>
<body>
    <div id="templatemo_menu_wrapper">

        <div id="templatemo_menu">

            <ul>
                <li><a href="@Url.Action("Index", "Bookstore")" class="current">Home</a></li>

                <li>
                    <a href="@Url.Action("DangKy", "NguoiDung")" target="_parent">Đăng ký</a>
                </li>
                <li>
                    <a href="@Url.Action("DangNhap", "NguoiDung")" target="_parent">Đăng nhập</a>
                </li>
                <li>
                   
                    <a href="@Url.Action("GioHang", "GioHang")" target="_parent">Giỏ hàng</a>

                </li>
                <li>
                    @Html.Action("GiohangPartial", "GioHang")
                </li>

            </ul>

        </div> <!-- end of templatemo_menu -->

    </div> <!-- end of templatemo_menu_wrapper -->

    <div id="templatemo_header_wrapper">

        <div id="templatemo_header">

            <div id="site_title">

                <h1>
                    <a href="#" target="_parent">
                        <img src="../images/templatemo_logo.png" alt="Site Title" />
                       
                    </a>
                </h1>

            </div> <!-- end of site_title -->

        </div> <!-- end of templatemo_header -->

    </div> <!-- end of templatemo_header_wrapper -->

    <div id="templatemo_slider_wrapper">

        <div id="templatemo_slider">

            <div id="latest_product_slider">

                <div id="SlideItMoo_outer">
                    <div id="SlideItMoo_inner">
                        <div id="SlideItMoo_items">
                            <div class="SlideItMoo_element">
                                <a href="#">
                                    <img src="../images/templatemo_product_01.png" alt="product 1" />
                                </a>

                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#">
                                    <img src="../images/templatemo_product_02.png" alt="product 2" />
                                </a>

                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#">
                                    <img src="../images/templatemo_product_03.png" alt="product 3" />
                                </a>

                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#">
                                    <img src="../images/templatemo_product_04.png" alt="product 4" />
                                </a>

                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#">
                                    <img src="../images/templatemo_product_05.png" alt="product 5" />
                                </a>

                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#">
                                    <img src="../images/templatemo_product_06.png" alt="product 6" />
                                </a>

                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#">
                                    <img src="../images/templatemo_product_07.png" alt="product 7" />
                                </a>
                            </div>
                            <div class="SlideItMoo_element">
                                <a href="#">
                                    <img src="../images/templatemo_product_08.png" alt="product 8" />
                                </a>

                            </div>
                        </div>
                    </div>
                </div>

            </div> <!-- end of latest_product_slider -->

        </div> <!-- end of templatemo_slider -->

    </div> <!-- end of templatemo_slider_wrapper -->

    <div id="templatemo_content_wrapper">
        <div id="templatmeo_sidebar">
            <div class="sidebar_section">
                <h2>Search Any Item</h2>
                <div class="sidebar_section_content">
                    <form action="#" method="get">
                        <input type="text" value="Enter a keyword..." name="q" size="10" id="searchfield" title="searchfield" onfocus="clearText(this)" onblur="clearText(this)" />
                        <input type="submit" name="Search" value="Search" alt="Search" id="searchbutton" title="Search" />
                    </form>
                    <div class="cleaner"></div>
                </div>
            </div>
            <div class="sidebar_section">

                <h2>Chủ đề sách</h2>

                <div class="sidebar_section_content">
                    @Html.Action("Topic", "BookStore")
                </div>
            </div>
            <div class="sidebar_section">

                <h2>Nhà xuất bản</h2>
                <div class="sidebar_section_content">
                    @Html.Action("NhaXuatBan", "BookStore");
                </div>
                
            </div>

        </div> <!-- end of templatemo_slider -->

        <div id="templatemo_content">
            <div class="content_section">

                <h2>Welcome to the Shoe Store</h2>

                <p><a href="http://www.templatemo.com/page/1" target="_parent">Free CSS Templates</a> are provided by <a href="http://www.templatemo.com" target="_parent">templatemo.com</a> for everyone. Feel free to download, edit and use this template for your websites.Validate <a href="http://validator.w3.org/check?uri=referer">XHTML</a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a>. Credit goes to <a href="http://www.vectorvaco.com" target="_blank">Free Vectors</a> for vector graphics used in this layout.</p>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et quam vitae ipsum vulputate varius vitae semper nunc. Quisque eget elit quis augue pharetra feugiat. <a href="#">Suspendisse</a> turpis arcu, dignissim ac laoreet a, <a href="#">condimentum</a> in massa.</p>

            </div>

            <div class="content_section">

          
              

                    @RenderBody();

               
                <div class="cleaner"></div>

            </div>

        </div> <!-- end of templatemo_content -->

        <div class="cleaner"></div>

    </div> <!-- end of templatemo_content_wrapper -->

    <div id="templatemo_footer">

        <ul class="footer_menu">
            <li><a href="#">Home</a></li>
            <li><a href="#">Products</a></li>
            <li><a href="#">News</a></li>
            <li><a href="#">Gallery</a></li>
            <li class="last_menu"><a href="#">Contact</a></li>
        </ul>

        Copyright © 2048 <a href="#">Your Company Name</a> |
        <a href="http://www.iwebsitetemplate.com" target="_parent">Website Templates</a> by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a>
    </div>
    <!-- end of footer -->

</body>
</html>